# -*- coding: utf-8 -*-
"""MergeAwds-Cuentas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1keIXFIcThj8_jaVz0ZlnU4eet0upANqs
"""

import pandas as pd

df1 = pd.read_csv("/content/AWD_barrido-2026-07-17.csv")
df2 = pd.read_excel("/content/Total de Cuentas Comerciales.xlsx",sheet_name='Cuentas')
df3 = pd.read_excel("/content/Agencias con AWD.xlsx")

#aseguramos mismo tipo

for df in [df1, df2, df3]:
    df['AWD'] = df['AWD'].astype(str).str.strip().str.upper()

df2 = df2.drop_duplicates(subset='AWD')
df3 = df3.drop_duplicates(subset='AWD')

df1.head()

#agregar la columna de autosustituto y Corporativo
df1['auto_sustituto'] = None
df1	['Corporativo'] = None

df3.columns = df3.columns.str.strip() # Clean column names for df3 to remove leading/trailing spaces

df_ref = df2.merge(
    df3[['AWD', 'Ejecutivo', 'Fecha Ingreso']],
    on='AWD',
    how='outer',
    suffixes=('_df2', '_df3')
)

# Ejecutivo
df_ref['Ejecutivo'] = df_ref['Ejecutivo_df2']
df_ref.loc[
    df_ref['Ejecutivo'].isna(),
    'Ejecutivo'
] = df_ref['Ejecutivo_df3']

# Fecha
df_ref['Fecha Ingreso'] = df_ref['Fecha Ingreso_df2']
df_ref.loc[
    df_ref['Fecha Ingreso'].isna(),
    'Fecha Ingreso'
] = df_ref['Fecha Ingreso_df3']

df_ref = df_ref[['AWD', 'AutoSustituto', 'Ejecutivo', 'Fecha Ingreso']]

df_ref.head()

df_final = df1.merge(df_ref, on='AWD', how='left')

df_final.head()

df_final['auto_sustituto'] = df_final['AutoSustituto']
df_final['FechaIngreso'] = df_final['Fecha Ingreso']

AWDS_ref = set(df2["AWD"]).union(set(df3["AWD"]))
df_final['Corporativo'] = df_final['AWD'].isin(AWDS_ref)

df_final = df_final.drop(columns=[
    'AutoSustituto',
    'Fecha Ingreso',
    'AWD_res',
    'ReservationId',
    'Booking_Date'
], errors='ignore')

df_final.head()

# ¿Cuántos AWDs totales?
len(df_final)

# ¿Cuántos sin Ejecutivo?
df_final['Ejecutivo'].isna().sum()
# ¿Duplicados?
df_final['AWD'].duplicated().sum()

awds_df1 = set(df_final["AWD"])
awds_ref = set(df_ref["AWD"])

awds_faltantes = awds_ref - awds_df1

df_faltantes = df_ref[df_ref['AWD'].isin(awds_faltantes)]

df_faltantes.head()

#df_final.to_csv("AWDs-cruce-cuentas.csv", encoding='utf-8-sig', index=False)
df_final.to_excel("AWDS-informacion-completa-21.xlsx", index=False)
df_final.to_csv("AWDS-informacion-completa-21-csv.csv", index=False)

df_faltantes.to_csv("AWDs_faltantes_cruce.csv", encoding='utf-8-sig', index=False)
df_faltantes.to_excel("AWDs_faltantes_cruce.xlsx", index=False)